CREATE EXTENDED STORAGE SIZE 10 GB ENABLE DELTA;
IMPORT ALL AS BINARY FROM '/hana/media/demo/exportDT/' WITH REPLACE THREADS 10;
update "DTDEMO"."Sales_Facts_retail" set "Date" = TO_NVARCHAR( ADD_YEARS (TO_DATE ("Date", 'YYYYMMDD'), 2), 'YYYYMMDD');
